services:
  web:
    build: .
    container_name: pin_people_web
    volumes:
      - .:/app
      - coverage_data:/app/htmlcov
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - RUN_MIGRATIONS=true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - pin_net

  worker:
    build: .
    container_name: pin_people_worker
    command: celery -A src.celery_app.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - RUN_MIGRATIONS=false
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - pin_net

  beat:
    build: .
    container_name: pin_people_beat
    command: celery -A src.celery_app.celery beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - RUN_MIGRATIONS=false
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - pin_net

  db:
    image: postgres:17
    container_name: pin_people_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
#    ports:
#      - "5432:5432"
    networks:
      - pin_net

  redis:
    image: redis:6.0.17-alpine
    container_name: pin_people_redis
    networks:
      - pin_net

  nginx:
    image: nginx:1.25-alpine
    container_name: pin_people_nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - coverage_data:/usr/share/nginx/html/htmlcov
    depends_on:
      - web
    networks:
      - pin_net

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: pin_people_cloudflare_tunnel
    restart: always
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - nginx
    networks:
      - pin_net

volumes:
  postgres_data:
  coverage_data:

networks:
  pin_net:
    driver: bridge